config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/sign_in_email' => 'omniauth_callbacks#sign_in_email'
  end

  root 'questions#index'

  concern :votable do
    member do
      get :like
      get :unlike
    end
  end

  resources :attachments, only: :destroy
  resources :questions, concerns: [:votable] do
    member do
      put :unsubscribe
    end
    resources :answers, concerns: [:votable] do
      member do
        put :best
      end
      resources :comments, only: [:create], defaults: { context: 'answer' }
    end
    resources :comments, only: [:create], defaults: { context: 'question' }
    resources :follows, only: [:create, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions, except: [:edit, :update, :destroy] do
        resources :answers, except: [:edit, :update, :destroy]
      end
    end
  end

  resources :users, only: [:index, :show] do
    member do
      put :change_daily_digest
    end
  end

  mount ActionCable.server => '/cable'

  get 'search', to: 'searches#index'
  post '/search_result', to: 'searches#search'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :follows, as: :followable, dependent: :destroy

  validates :title, :body, presence: true

  scope :ordered_question, -> { order(created_at: :desc) }
  scope :last_questions, -> { where(created_at: (Time.now - 24.hours)..Time.now) }

  def change_subscr
    update(check_follow: !check_follow)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  load_and_authorize_resource

  def index
    @questions = Question.all.ordered_question
    respond_with @questions
  end

  def show
    respond_with @question
  end

  def create
    respond_with @question = current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy, :unsubscribe]
  before_action :build_answer_comment, only: :show
  after_action :publish_question, only: [:create]

  respond_to :js

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    respond_with(@question = Question.new, layout: false)
  end

  def edit
    render :edit, layout: false
  end

  def create
    respond_with(@question = Question.create(question_params.merge(user_id: current_user.id)))
  end

  def update
    @question.update(question_params.merge(user_id: current_user.id))
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy) if current_user.author?(@question)
  end

  def unsubscribe
    respond_with(@question.change_subscr)
  end

  private

  def set_question
    @question = Question.find(params[:id])
    gon.question_id = @question.id
  end

  def build_answer_comment
    @answer = Answer.new
    @comment = Comment.new
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      render_to_string(template: 'questions/question.json.jbuilder')
    )
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/views/questions/_answer.html.haml
- cache_unless user_signed_in?, answer do
  %div{id: "answer_#{answer.id}"}
    .col-md-offset-1
      %strong
        = answer.user.name
        = "added #{time_ago_in_words answer.created_at} ago"
      %br
    .col-md-1
      = render 'common/rating_answers', resource: answer
    .col-md-11
      = answer.body
    .col-md-offset-1
      %h5 Attachments:
      - answer.attachments.each do |a|
        - cache_unless user_signed_in?, a do
          %div{id: "attachment_#{a.id}"}
            = link_to a.file.identifier, a.file.url
            - if can? :destroy, a
              = link_to '', a, class: "glyphicon glyphicon-remove", method: :delete, remote: true
    .col-md-offset-11.col-md-3
      - if can? :create, Comment
        = link_to '', '', class: "glyphicon glyphicon-comment answer-comment-link", data: { answer_id: answer.id }
      - if user_signed_in?
        = best_btn(@question, answer)
      - if can? :update, answer
        = link_to '', '', class: "glyphicon glyphicon-pencil edit-answer-link", data: { answer_id: answer.id }
        = link_to '', [@question, answer], method: :delete, remote: true, class: "glyphicon glyphicon-remove"
    .col-md-offset-1
      %hr
    .col-md-offset-1
      = render 'comments/answer_comment_form', answer: answer

      - if answer.comments.present?
        %h6
          = "#{answer.comments.count} Comments"
      %div{id: "comment_answer_#{answer.id}"}
        - answer.comments.each do |comment|
          = render 'comments/comment', comment: comment

      = simple_form_for([@question, answer], remote: true, html: { id: "edit-answer-#{answer.id}" }) do |f|
        .answer_errors
        = f.input :body, label: false, placeholder: 'Your answer'
        = f.submit "Edit", class: "btn btn-primary btn-sm"

app/views/questions/_answers.html.haml
- @question.answers.includes(:user, :attachments, comments: :user).ordered.each do |answer|
  = render 'questions/answer', answer: answer

app/views/questions/_attachment_fields.html.haml
.nested-fields
  = f.input :file, as: :file
  = link_to_remove_association "Delete", f

app/views/questions/_buttons.html.haml
- if can? :create, Question
  .col-md-offset-8.col-md-4
    = link_to "My profile", user_path(current_user), class: "btn btn-primary btn-sm"
    = link_to "Users", users_path, class: "btn btn-primary btn-sm"
    = link_to "Search", search_path, class: "btn btn-primary btn-sm"
    = link_to "Ask question", new_question_path, class: "btn btn-primary btn-sm", "data-target": "#new_modal", "data-toggle": "modal"
    #new_modal.modal.fade
      .modal-dialog
        .modal-content

app/views/questions/_buttons_follow.html.haml
.follow_btn
  - if can? :create, Question
    .col-md-offset-7.col-md-5
      - if !current_user.author?(question)
        = follow_btn(question)
      - else
        = unsubscribe_btn(question)
      = link_to "My profile", user_path(current_user), class: "btn btn-primary btn-sm"
      = link_to "Users", users_path, class: "btn btn-primary btn-sm"
      = link_to "Search", search_path, class: "btn btn-primary btn-sm"
      = link_to "Ask question", new_question_path, class: "btn btn-primary btn-sm", "data-target": "#new_modal", "data-toggle": "modal"
      #new_modal.modal.fade
        .modal-dialog
          .modal-content

app/views/questions/_form.html.haml
.modal-header
  = button_to '#', data: { dismiss: 'modal' }, class: 'close' do
    = content_tag :span, 'x'
  %h4.modal-title
    = "#{@question.new_record? ? 'Ask question' : 'Edit question'}"
.modal-body
  = simple_form_for(@question) do |f|
    = bootstrap_devise_error_messages!(@question)
    .form-group
      = f.input :title, label: false, placeholder: 'Title', input_html: { value: "#{@question.new_record? ? '' : @question.title}" }, hint: 'Can\'t be empty'
      = f.input :body, label: false, placeholder: 'Your question', input_html: { value: "#{@question.new_record? ? '' : @question.body}" }, hint: 'Can\'t be empty'
      = f.simple_fields_for :attachments do |a|
        = render 'attachment_fields', f: a
      .links
        = link_to_add_association 'Attach file', f, :attachments
      .modal-footer
        = button_to 'Cancel', '#', class: 'btn btn-default btn-sm', data: { dismiss: 'modal' }
        = f.submit  "#{@question.new_record? ? 'Save' : 'Edit'}", class: "btn btn-primary btn-sm create-question"

app/views/questions/_links.html.haml
.col-md-offset-11.col-md-1
  - if can? :update, question
    = link_to '', edit_question_path(question), class: "glyphicon glyphicon-pencil", "data-target": "#edit_modal", "data-toggle": "modal"
    #edit_modal.modal.fade
      .modal-dialog
        .modal-content
    = link_to '', question, class: "glyphicon glyphicon-remove", method: :delete, data: { confirm: 'Are you sure?' }

app/views/questions/_links_comment.html.haml
.col-md-offset-11.col-md-3
  - if can? :create, Comment
    = link_to '', '', class: "glyphicon glyphicon-comment question-comment-link"
  - if can? :update, question
    = link_to '', edit_question_path(question), class: "glyphicon glyphicon-pencil", "data-target": "#edit_modal", "data-toggle": "modal"
    #edit_modal.modal.fade
      .modal-dialog
        .modal-content
    = link_to '', question, class: "glyphicon glyphicon-remove", method: :delete, data: { confirm: 'Are you sure?' }

app/views/questions/edit.html.haml
= render 'form'

app/views/questions/index.html.haml
.container
  .row
    = render 'buttons'
    .col-md-offset-1.col-md-10.col-md-offset-1
      .list-questions
        - cache_unless user_signed_in?, @questions do
          - @questions.ordered_question.each do |question|
            %h4= link_to "#{question.title}", question

            = question.body
            %br/
            = render 'links', question: question

app/views/questions/new.html.haml
= render 'form'

app/views/questions/show.html.haml
- cache_unless user_signed_in?, @question do
  .container
    .row
      = render 'buttons_follow', question: @question
      .question
        %div
          .col-md-offset-1.col-md-11
            %h4
              = @question.user.name
              %p= @question.title
          .col-md-1
            = render 'common/rating_question', resource: @question
          .col-md-11
            = @question.body
          .col-md-offset-1
            %h5 Attachments:
            - @question.attachments.each do |a|
              - cache_unless user_signed_in?, a do
                %div{id: "attachment_#{a.id}"}
                  = link_to a.file.identifier, a.file.url
                  - if can? :destroy, a
                    = link_to '', a, class: "glyphicon glyphicon-remove", method: :delete, remote: true

            = render 'links_comment', question: @question
            %hr
            = render 'comments/question_comment_form'

            - if @question.comments.present?
              %h6
                = "#{@question.comments.count} Comments"
            .comments
              - @question.comments.ordered_comment.each do |comment|
                = render 'comments/comment', comment: comment

          - if @question.answers.present?
            .col-md-offset-1
              %h4
                = "#{@question.answers.count} Answers"
          .answers
            = render 'questions/answers'

          .col-md-offset-1
            - if can? :create, Answer
              .new_answer_form
                = simple_form_for([@question, @answer], remote: true) do |f|
                  .answer_errors
                  = f.input :body, label: false, placeholder: 'Your answer'
                  = f.simple_fields_for :attachments do |a|
                    = render 'attachment_fields', f: a
                  .links
                    = link_to_add_association 'Attach file', f, :attachments
                  = f.submit "Save", class: "btn btn-primary btn-sm"

app/views/questions/unsubscribe.js.erb
$('.follow_btn').html("<%= j render 'questions/buttons_follow', question: @question %>");