config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/sign_in_email' => 'omniauth_callbacks#sign_in_email'
  end

  root 'questions#index'

  concern :votable do
    member do
      get :like
      get :unlike
    end
  end

  resources :attachments, only: :destroy
  resources :questions, concerns: [:votable] do
    member do
      put :unsubscribe
    end
    resources :answers, concerns: [:votable] do
      member do
        put :best
      end
      resources :comments, only: [:create], defaults: { context: 'answer' }
    end
    resources :comments, only: [:create], defaults: { context: 'question' }
    resources :follows, only: [:create, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions, except: [:edit, :update, :destroy] do
        resources :answers, except: [:edit, :update, :destroy]
      end
    end
  end

  resources :users, only: [:index, :show] do
    member do
      put :change_daily_digest
    end
  end

  mount ActionCable.server => '/cable'

  get 'search', to: 'searches#index'
  post '/search_result', to: 'searches#search'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  skip_authorization_check

  def index; end

  def search
    type = params[:search][:type]
    value = params[:search][:value]

    @result = if type == 'Global'
                ThinkingSphinx.search ThinkingSphinx::Query.escape(value)
              else
                type.classify.constantize.search ThinkingSphinx::Query.escape(value)
              end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
  def types_of_search
    %w(Global User Question Answer Comment)
  end
end

app/views/searches/_search_result.html.haml
%br
- if result.empty?
  %h4
    = "#{result.size} results"
    %br
    = "Your search returned no matches."
- else
  %h4
    = "#{result.size} results"
  - result.each do |r|
    - if r.class.name == 'Question'
      = "Type: #{r.class.name}"
      %br
      = "Author: #{r.user.name}"
      %br
      = link_to "Title: #{r.title}", question_url(r)
      %br
      = "Body: #{r.body}"
      %hr
    - elsif r.class.name == 'Answer'
      = "Type: #{r.class.name}"
      %br
      = "Author: #{r.user.name}"
      %br
      = link_to "Body: #{r.body}", question_url(r.question)
      %hr
    - elsif r.class.name == 'Comment'
      - r.commentable.class.name == 'Question' ? comment_url = r.commentable : comment_url = r.commentable.question
      = "Type: #{r.class.name}"
      %br
      = "Author: #{r.user.name}"
      %br
      = link_to "Body: #{r.body}", question_url(comment_url)
      %hr
    - elsif r.class.name == 'User'
      = "Type: #{r.class.name}"
      %br
      = "Name: #{r.name}"
      %br
      = "Email: #{r.email}"
      %hr

app/views/searches/index.html.haml
.container
  .row
    = render 'questions/buttons'
    .col-md-offset-1.col-md-10.col-md-offset-1
      = simple_form_for(:search, url: search_result_path, remote: true) do |f|
        = f.input :type, collection: types_of_search, label: "Choose type"
        = f.input :value, label: false, placeholder: 'Add something...'
        = f.submit "Search", class: "btn btn-primary btn-sm"
      .result

app/views/searches/search.js.erb
$('.result').html("<%= j render 'search_result', result: @result %>");