config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/sign_in_email' => 'omniauth_callbacks#sign_in_email'
  end

  root 'questions#index'

  concern :votable do
    member do
      get :like
      get :unlike
    end
  end

  resources :attachments, only: :destroy
  resources :questions, concerns: [:votable] do
    member do
      put :unsubscribe
    end
    resources :answers, concerns: [:votable] do
      member do
        put :best
      end
      resources :comments, only: [:create], defaults: { context: 'answer' }
    end
    resources :comments, only: [:create], defaults: { context: 'question' }
    resources :follows, only: [:create, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions, except: [:edit, :update, :destroy] do
        resources :answers, except: [:edit, :update, :destroy]
      end
    end
  end

  resources :users, only: [:index, :show] do
    member do
      put :change_daily_digest
    end
  end

  mount ActionCable.server => '/cable'

  get 'search', to: 'searches#index'
  post '/search_result', to: 'searches#search'
end

app/views/common/_errors.html.haml
.col-md-4
  = bootstrap_devise_error_messages!(resource)

app/views/common/_exception.js.erb
alert("<%= resource.message %>");

app/views/common/_rating_answers.html.haml
- cache_unless user_signed_in?, resource do
  - if user_signed_in?
    = link_to '', like_question_answer_path(@question, resource), remote: true, class: "glyphicon glyphicon-triangle-top vote-answer", data: { type: :json }
    %div{id: "rating_#{resource.id}"}
      = resource.rating
    = link_to '', unlike_question_answer_path(@question, resource), remote: true, class: "glyphicon glyphicon-triangle-bottom vote-answer", data: { type: :json }

app/views/common/_rating_question.html.haml
- cache_unless user_signed_in?, resource do
  .questions
    - if user_signed_in?
      = link_to '', like_question_path(resource), remote: true, class: "glyphicon glyphicon-triangle-top votes question-like", data: { type: :json }
      .rating
        = resource.rating
      = link_to '', unlike_question_path(resource), remote: true, class: "glyphicon glyphicon-triangle-bottom votes question-unlike", data: { type: :json }

app/views/common/add_email.html.haml
.container
  .row
    .col-md-offset-3.col-md-6.col-md-offset-3
      .panel.panel-default.devise-bs
        .panel-heading
          %h4= "Add Email"
        .panel-body
          = form_tag sign_in_email_path, method: :post do
            .form-group
              = label_tag 'Email'
              = email_field 'auth[info]', :email, autofocus: true, class: "form-control", id: "add-email", placeholder: "Can't be empty"
            = hidden_field_tag 'auth[info][name]', auth[:info][:name] || auth[:info][:nickname]
            = hidden_field_tag 'auth[provider]', auth[:provider]
            = hidden_field_tag 'auth[uid]', auth[:uid]
            = submit_tag 'Save', class: "btn btn-primary sendButton"